apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vector-db-engine.fullname" . }}
  labels:
    {{- include "vector-db-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vector-db-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vector-db-engine.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.existingSecret }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "vector-db-engine.fullname" . }}-secret
                  key: API_KEY  
          {{- end }}

