apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector-db-engine.fullname" . }}
  labels:
    {{- include "vector-db-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "vector-db-engine.selectorLabels" . | nindent 4 }}
